In [81]:
import pandas as pd
import numpy as np

In [83]:
df1=pd.read_csv('F:/Python/Ostad Python/Jupyter notebook/NB_NLP_HAM-SPAM_Identification/spam.csv')
df1

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [85]:
df1.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [87]:
df1.shape

(5572, 2)

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df1.Message, df1.Category, test_size=0.2, random_state=42)

In [91]:
X_train

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
                              ...                        
3772    Hi, wlcome back, did wonder if you got eaten b...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860               Did he just say somebody is named tampa
Name: Message, Length: 4457, dtype: object

In [93]:
X_test

3245    Squeeeeeze!! This is christmas hug.. If u lik ...
944     And also I've sorta blown him off a couple tim...
1044    Mmm thats better now i got a roast down me! i’...
2484        Mm have some kanji dont eat anything heavy ok
812     So there's a ring that comes with the guys cos...
                              ...                        
4264    Den only weekdays got special price... Haiz......
2439         I not busy juz dun wan 2 go so early.. Hee..
5556    Yes i have. So that's why u texted. Pshew...mi...
4205    How are you enjoying this semester? Take care ...
4293                                                G.W.R
Name: Message, Length: 1115, dtype: object

In [95]:
y_train

1978    spam
3989     ham
3935     ham
4078     ham
4086    spam
        ... 
3772     ham
5191     ham
5226     ham
5390     ham
860      ham
Name: Category, Length: 4457, dtype: object

In [97]:
y_test

3245    ham
944     ham
1044    ham
2484    ham
812     ham
       ... 
4264    ham
2439    ham
5556    ham
4205    ham
4293    ham
Name: Category, Length: 1115, dtype: object

In [99]:
X_train.values

array(['Reply to win £100 weekly! Where will the 2006 FIFA World Cup be held? Send STOP to 87239 to end service',
       'Hello. Sort of out in town already. That . So dont rush home, I am eating nachos. Will let you know eta.',
       'How come guoyang go n tell her? Then u told her?', ...,
       "Prabha..i'm soryda..realy..frm heart i'm sory",
       'Nt joking seriously i told',
       'Did he just say somebody is named tampa'], dtype=object)

In [101]:
X_train.values.shape

(4457,)

In [103]:
type(X_train.values)

numpy.ndarray

## Create bag of words representation using CountVectorizer OR BEGAPOD METHOD

In [105]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7701 sparse matrix of type '<class 'numpy.int64'>'
	with 59275 stored elements in Compressed Sparse Row format>

In [107]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [109]:
X_train_cv.shape

(4457, 7701)

In [111]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [113]:
#ALL ROW  52816 FOLLOW CODE
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'èn', 'ú1'], dtype=object)

In [115]:
pd.DataFrame(X_train_cv.toarray(), columns=v.get_feature_names_out())

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  02  \
0      0    0       0             0     0     0            0            0   0   
1      0    0       0             0     0     0            0            0   0   
2      0    0       0             0     0     0            0            0   0   
3      0    0       0             0     0     0            0            0   0   
4      0    0       0             0     0     0            0            0   0   
...   ..  ...     ...           ...   ...   ...          ...          ...  ..   
4452   0    0       0             0     0     0            0            0   0   
4453   0    0       0             0     0     0            0            0   0   
4454   0    0       0             0     0     0            0            0   0   
4455   0    0       0             0     0     0            0            0   0   
4456   0    0       0             0     0     0            0            0   0   

      0207  ...  zeros  zhong  zindgi  zoe  zogtorius  zoom  zouk  zyada  èn  \
0        0  ...      0      0       0    0          0     0     0      0   0   
1        0  ...      0      0       0    0          0     0     0      0   0   
2        0  ...      0      0       0    0          0     0     0      0   0   
3        0  ...      0      0       0    0          0     0     0      0   0   
4        0  ...      0      0       0    0          0     0     0      0   0   
...    ...  ...    ...    ...     ...  ...        ...   ...   ...    ...  ..   
4452     0  ...      0      0       0    0          0     0     0      0   0   
4453     0  ...      0      0       0    0          0     0     0      0   0   
4454     0  ...      0      0       0    0          0     0     0      0   0   
4455     0  ...      0      0       0    0          0     0     0      0   0   
4456     0  ...      0      0       0    0          0     0     0      0   0   

      ú1  
0      0  
1      0  
2      0  
3      0  
4      0  
...   ..  
4452   0  
4453   0  
4454   0  
4455   0  
4456   0  

[4457 rows x 7701 columns]

In [117]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [121]:
X_test

3245    Squeeeeeze!! This is christmas hug.. If u lik ...
944     And also I've sorta blown him off a couple tim...
1044    Mmm thats better now i got a roast down me! i’...
2484        Mm have some kanji dont eat anything heavy ok
812     So there's a ring that comes with the guys cos...
                              ...                        
4264    Den only weekdays got special price... Haiz......
2439         I not busy juz dun wan 2 go so early.. Hee..
5556    Yes i have. So that's why u texted. Pshew...mi...
4205    How are you enjoying this semester? Take care ...
4293                                                G.W.R
Name: Message, Length: 1115, dtype: object

#### SIMILARLY DO BEGAPOD FOR X_TEST

In [123]:
X_test_cv = v.transform(X_test)

In [125]:
X_test_cv.toarray().shape

(1115, 7701)

In [127]:
model.score(X_test_cv, y_test)

0.9919282511210762

In [129]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      1.00       966
        spam       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



## Now Input new prediction data for fake news 

In [147]:
email_dataset = [
   "Congratulations! You won $1,000,000!",#(Spam) 
"Increase Your Credit Score Instantly",#(SPAM)
"You've Won $1,000,000!",#(SPAM)
"Password Reset Request",#(SPAM)
"Team Meeting Reminder", #(HAM)
]

In [149]:
emails_count = v.transform(email_dataset)
emails_count.toarray().shape

(5, 7701)

In [151]:
emails_count.toarray()

array([[0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [153]:
#emails_count.toarray().shape
model.predict(emails_count)

array(['spam', 'spam', 'spam', 'ham', 'ham'], dtype='<U4')